// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6n8x4hrqEhvxrtxBKwwhGwZWii7p0vqY',
    appId: '1:677388642166:web:c834a8105849e971ca3c57',
    messagingSenderId: '677388642166',
    projectId: 'fir-c0cae',
    authDomain: 'fir-c0cae.firebaseapp.com',
    storageBucket: 'fir-c0cae.firebasestorage.app',
    measurementId: 'G-2M9H2BY10F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4w6O9Z-ghpHianKL4oLgtkX4jjFassPE',
    appId: '1:677388642166:android:3b16339456539bc6ca3c57',
    messagingSenderId: '677388642166',
    projectId: 'fir-c0cae',
    storageBucket: 'fir-c0cae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeB4PpcPcn-4rsPaSnZPTNz_aRKTdFaug',
    appId: '1:677388642166:ios:265a152ee9145837ca3c57',
    messagingSenderId: '677388642166',
    projectId: 'fir-c0cae',
    storageBucket: 'fir-c0cae.firebasestorage.app',
    iosBundleId: 'com.example.youtubefirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeB4PpcPcn-4rsPaSnZPTNz_aRKTdFaug',
    appId: '1:677388642166:ios:265a152ee9145837ca3c57',
    messagingSenderId: '677388642166',
    projectId: 'fir-c0cae',
    storageBucket: 'fir-c0cae.firebasestorage.app',
    iosBundleId: 'com.example.youtubefirebase',
  );
}
